[phases.setup]
nixPkgs = [
    "bash",
    "php83",
    "php83Extensions.pdo_sqlite",
    "php83Extensions.sqlite3",
    "php83Extensions.pdo_mysql",
    "php83Extensions.pdo_pgsql",
    "composer",
    "nodejs_20"
]

[phases.build]
cmds = [
     "composer install --no-dev --optimize-autoloader --no-interaction --prefer-dist",
     "npm ci",
     "npm run build",
    "mkdir -p storage/framework/{sessions,views,cache}",
    "mkdir -p bootstrap/cache",
    "mkdir -p database",
    "touch database/database.sqlite"
]

[start]
cmd = "bash scripts/start.sh"
